### ISSUE TITLE
Add CI/CD Version Bump Debug Annotations

### ISSUE THREAD

**Issue by goingforbrooke** [goingforbrooke/folsum#18]
## Issue
When CI/CD pipelines fail, the first thing that I want to know is whether it was trying to increment the minor or patch/fix (SemVer) version.

## Solution

Use `::notice::` to annotate the output of the following CI/CD steps in `build_macos.yml`:
- `Get the last branch that was merged into the `dev` branch`
- `Decide whether to bump the minor or patch version`
- `Increment minor/patch version`

```yaml
      - name: Generate "new release" message with hyperlink to release page
        id: generate_release_message
        run: echo "message=Created new release ${{ steps.get_bumped_semver.outputs.semver }} at ${{ steps.publish_release.outputs.html_url }}" >> $GITHUB_OUTPUT
      - name: Create info message about new release
        run: echo "::notice::${{ steps.generate_release_message.outputs.message }}"
```
